version: '2.1'

services:

  activemq:
    image: rmohr/activemq:latest
    ports:
      - "61616:61616"
      - "8161:8161"
    volumes:
      - "./activemq.xml:/opt/apache-activemq-5.15.6/conf/activemq.xml:ro"
      - "./jetty.xml:/opt/apache-activemq-5.15.6/conf/jetty.xml:ro"
      - "./camel.xml:/opt/apache-activemq-5.15.6/conf/camel.xml:ro"
